{ stdenv, lib, unzip }:

stdenv.mkDerivation {
  pname = "plymouth-theme-precision-clock-boot";
  version = "1.0";

  src = ./precision_clock_boot.zip;

  nativeBuildInputs = [ unzip ];

  sourceRoot = ".";

  installPhase = ''
    mkdir -p $out/share/plymouth/themes

    # Copy the generated theme directory (frames + .script + .plymouth)
    cp -r precision_clock_boot $out/share/plymouth/themes/

    # Point the .plymouth ImageDir/ScriptFile paths at the nix store
    find $out/share/plymouth/themes/ -name \*.plymouth \
      -exec sed -i "s@/usr/@$out/@" {} \;
  '';

  meta = with lib; {
    description = ''
      Precision clock boot splash for the 960x240 ST7701 panel: an SMPTE test
      card that loses signal into TV snow which then piles into a QAM
      constellation, handing off to a seamless idle loop with a discrete
      vectorscope phasor. Generated by precision_clock_boot.py.
    '';
    platforms = platforms.linux;
  };
}
